//error handling 

// try{
//     console.log(a)
// }
// catch(err){
//     console.log("Something went wrong");
// }


// try{
//     console.log(a)
// }
// catch(err){
//     console.log(err)
// }